import Head from "next/head";
//import styles from "@/styles/Home.module.css";
import Login from "./login";
import { useSession } from "@supabase/auth-helpers-react";
import Account from "./components/account";

export default function Home() {
  const session = useSession();

  return (
    <>
      <Head>
        <title>Pocketrip</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-screen w-full">
        <div className="container" style={{ padding: "50px 0 100px 0" }}>
          {!session ? <Login /> : <Account session={session} />}
        </div>
      </main>
    </>
  );
}
